on:
  push:


jobs:
  create-windows-installer:
    name: Create Windows Installer
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '14.0.2'
          java-package: jdk
          architecture: x64
      - name: Build application w Gradle
        run: |
          cmd.exe /c 'gradlew.bat build'
      - name: Install Wix Tools
        run: |
          choco install wixtoolset -y
      - name: Build Installer
        run: |
          cmd.exe /c 'gradlew.bat jpackage'
      - name: Upload Windows Installer
        uses: actions/upload-artifact@v2
        with:
          name: windows-installer
          path: Demo/build/jpackage/*.msi


#  create-release:
#    name: Create a Github Release
#    runs-on: ubuntu-latest
#    steps:
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: v1.0
#          release_name: My Conflicted Test ReleaseK
#          draft: false
#          prerelease: true